package com.littlek4za.booking_system.exception.model;

public enum ErrorCode {
    // Guest
    GUEST_TOKEN_INVALID,
    GUEST_TOKEN_EXPIRED,
    CAPTCHA_INVALID,
    CAPTCHA_REQUIRED,
    USERNAME_ALREADY_REGISTERED,
    EMAIL_ALREADY_REGISTERED,
    

    // Auth
    UNAUTHORIZED,
    ACCESS_DENIED,
    TOKEN_INVALID,
    USER_NOT_FOUND,
    PASSWORD_INVALID,
    TOKEN_TYPE_INVALID,
    
    // Validation
    FIELD_VALIDATION_FAILED,

    // SYSTEM
    INVALID_STATE,
    INTERNAL_ERROR,
    INVALID_CAPTCHA,
    
    // Invitation
    INVITATION_NOT_FOUND,
    INVITATION_EXPIRED,
    INVITATION_MAX_USAGE_REACHED,
    INVITATION_USER_USAGE_LIMIT_REACHED,

    // Event
    EVENT_NOT_FOUND,
    EVENT_TYPE_INVALID,
    EVENT_TYPE_CHANGE_NOT_ALLOWED,

    // Slot
    SLOT_NOT_FOUND,
    SLOT_INCLUDE_MODE_INVALID,
    SLOT_FULL,
    SLOT_TIME_ALREADY_BOOKED,

    // Booking
    BOOKING_NOT_FOUND,
    BOOKING_REQUEST_INVALID,
    EVENT_BOOKING_LIMIT_REACHED,
    SLOT_BOOKING_LIMIT_REACHED,

    // Mismatch
    SLOT_EVENT_MISMATCH,
    SLOT_INVITATION_MISMATCH,
    SLOT_CONFIGURATION_INVALID,
    SLOT_UPDATE_NOT_ALLOWED,

    

}
